/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedUnderline: typeof import('./src/components/AnimatedUnderline.vue')['default']
    CardBody: typeof import('./src/components/3D/CardBody.vue')['default']
    CardCarousel: typeof import('./src/components/CardCarousel.vue')['default']
    CardContainer: typeof import('./src/components/3D/CardContainer.vue')['default']
    CardItem: typeof import('./src/components/3D/CardItem.vue')['default']
    CardSpotlight: typeof import('./src/components/CardSpotlight.vue')['default']
    GlowingCard: typeof import('./src/components/GlowingCard.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
